apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
     {{- include "vertx-ddd-template.labels" . | nindent 4 }}
data:
  config.yaml: |-
    server:
      host: 0.0.0.0
      port: {{ .Values.service.targetport }}
      context: {{ .Values.app.context }}
    thirdParties:
      xkcdJoke:
        url: {{ .Values.app.url }}
        retries: {{ .Values.app.retries }}
        email: {{ .Values.app.email }}
