apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertx-ddd-template.fullname" . }}
  labels:
    {{- include "vertx-ddd-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vertx-ddd-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vertx-ddd-template.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          env:
          - name: {{ .Values.env.name }}
            value: {{ .Values.env.value }}
          ports:
          - containerPort: {{ .Values.service.targetport }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config/
          - name: config-volume-secret
            mountPath: /etc/config/secret
            readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: config-volume-secret
        secret:
          secretName: mysecret
