apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  configsecret.yaml: |-
    apiUrl: {{ .Values.app.apiurl }}
    username: {{ .Values.app.username }}
    password: {{ .Values.app.password }}
