apiVersion: v1
kind: Service
metadata:
  name: {{ include "vertx-ddd-template.fullname" . }}
  labels:
    {{- include "vertx-ddd-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
  selector:
    {{- include "vertx-ddd-template.selectorLabels" . | nindent 4 }}
